name = "CartesianGrids"
uuid = "3e975e5d-2cf8-4263-9573-8460aaf534d9"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
repo = "https://github.com/JuliaIBPM/CartesianGrids.jl.git"
version = "0.1.30"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpaceTimeFields = "0af78db0-3b7c-4df8-88bd-686b7cc5245d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BenchmarkTools = "0.5, 0.7, 1"
ColorTypes = "<0.10.1, 0.10, 0.11"
FFTW = "^1"
FastGaussQuadrature = "0.4.2, 0.5"
ForwardDiff = "0.10.16"
Interpolations = "0.12.10, 0.13, 0.14"
LaTeXStrings = "^1.0, 1.1"
LinearAlgebra = "1.6"
PkgBenchmark = "0.2.10"
ProgressMeter = "^1.1"
RecipesBase = "1"
Reexport = "1"
Serialization = "1.6"
SpaceTimeFields = "0.2.0"
SparseArrays = "1.6"
SpecialFunctions = "0.8.0, 0.10, 1.2, 2"
Statistics = "1.6"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
